# Adopted from unicode's upstream, modified for our use-case https://github.com/unicode-org/icu/blob/99ca2ad931600f317501a41bca4c8b9afb946de9/.github/workflows/icu4c.yml#L394C1-L481C38

on:
  push:
    branches:
      - main
      # XXX: remove me after testing is complete
      - testing_gha
  pull_request: {}
  workflow_dispatch:
    inputs:
      gitReleaseTag:
        description: 'Release tag to upload to. Must start with "v"'
        type: string

jobs:
  # Windows MSVC distribution (conditional release)
  windows-msvc-dist-release:
    runs-on: windows-2022  # Updated in BRS
    permissions:
      contents: write # So that we can upload to release
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Set ICU_DATA_FILTER_FILE variable
      run: |
        $filterPath = "${{ github.workspace }}\build\filter.json"
        echo "ICU_DATA_FILTER_FILE=$filterPath" >> $GITHUB_ENV
      shell: pwsh
    - name: Set up MSBuild for x64
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Generate forwarding dlls x64
      run: |
        $VCPath = C:\\ProgramData\\Chocolatey\\bin\\vswhere.exe -products * -property installationPath -latest
        & "$VCPath\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64
        ./build/scripts/build_forwarding_dlls.bat x64

    - name: Build entire Solution x64
      run: |
        msbuild icu/icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x64 /p:SkipUWP=true
        msbuild icu/icu4c/source/common-and-i18n/combined.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Run Tests x64 (icucheck.bat)
      run: ./icu/icu4c/source/allinone/icucheck.bat x64 Release

    - name: Build entire Solution x86
      run: |
        msbuild icu4c/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=x86 /p:SkipUWP=true
        msbuild icu/icu4c/source/common-and-i18n/combined.vcxproj /p:Configuration=Release /p:Platform=x86
    - name: Run Tests x86 (icucheck.bat)
      run: ./icu/icu4c/source/allinone/icucheck.bat x86 Release
    - name: Generate forwarding dlls x86
      run: |
        iex "$(C:\\ProgramData\\Chocolatey\\bin\\vswhere.exe -products * -property installationPath -latest)\\VC\\Auxiliary\\Build\\vcvarsall.bat x86"
        ./build/scripts/build_forwarding_dlls.bat x86

    - name: "Run PowerShell: Distrelease script"
      run: |
        ./build/scripts/distrelease_overlay.ps1
      shell: pwsh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: icu4c.run_#${{ github.run_number }}
        path: icu/icu4c/source/dist/icu-win.tar.gz
    - name: Upload to release
      if: ${{ inputs.gitReleaseTag && startsWith(inputs.gitReleaseTag, 'v') }}
      run: |
        gh release upload ${{ inputs.gitReleaseTag }} icu4c/source/dist/icu-win.tar.gz --clobber
      env:
        GH_TOKEN: ${{ github.token }}